namespace ProEdit.Vba;

public enum VbaTokenKind
{
    EndOfFile,
    Identifier,
    Number,
    String,
    NewLine,
    Equal,
    NotEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Comma,
    LParen,
    RParen,
    Dot,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Ampersand,
    KeywordIf,
    KeywordThen,
    KeywordElse,
    KeywordAnd,
    KeywordOr,
    KeywordNot,
    KeywordFor,
    KeywordTo,
    KeywordStep,
    KeywordNext,
    KeywordDo,
    KeywordLoop,
    KeywordWhile,
    KeywordUntil,
    KeywordOn,
    KeywordError,
    KeywordResume,
    KeywordGoTo,
    KeywordSelect,
    KeywordCase,
    KeywordIs,
    KeywordWend,
    KeywordWith,
    KeywordReDim,
    KeywordPreserve,
    KeywordAs,
    KeywordDim,
    KeywordSet,
    KeywordExit,
    KeywordFunction,
    KeywordSub,
    KeywordEnd,
    KeywordCall,
    KeywordMod,
    KeywordPublic,
    KeywordPrivate,
    KeywordFriend,
    KeywordTrue,
    KeywordFalse
}

public readonly record struct VbaToken(
    VbaTokenKind Kind,
    string Text,
    int Position,
    int Line,
    int Column);
